config/routes.rb
Rails.application.routes.draw do

  get '/index' => 'pages#index'

  post '/contact_mailer' => 'pages#contact_mailer'

  root 'pages#index'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end

  def contact_mailer
    @email = params[:email]
    @content = params[:content]
    @phone = params[:phone]
    @name = params[:name]

    ContactMailer.contact(@email,@content,@phone).deliver_now
  end

  private


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
 <div class="brand">Business Casual</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
             
                        <%= link_to "Home", root_path %>
                    </li>
                    <li>
                 
                        <%= link_to "About", about_path %>
                    </li>
                    <li>
               
                        <%= link_to "Blog", blog_path %>
                    </li>
                    <li>
                        
                        <%= link_to "Contact", contact_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Kohl Kohlbrenner's personal site. ">
  <%= render 'layouts/shim' %>


</head>
<body class="theme-invert">
		<%= yield %>
</body>
</html>

app/views/pages/contact.html.erb
<%= provide(:title, "Contact - Kohl Kohlbrenner") %>

    <div class="container"> 

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                        <strong>business casual</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48388.11257552174!2d-74.36168805!3d40.7123578!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c3ae3f4c51b33d%3A0x90e229d96fad276f!2sSummit%2C+NJ!5e0!3m2!1sen!2sus!4v1430438369963"></iframe>
                </div>
                <div class="col-md-4">
                    <p>Phone:
                        <strong>123.456.7890</strong>
                    </p>
                    <p>Email:
                        <strong><a href="mailto:name@example.com">name@example.com</a></strong>
                    </p>
                    <p>Address:
                        <strong>3481 Melrose Place
                            <br>Beverly Hills, CA 90210</strong>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                        <strong>form</strong>
                    </h2>
                    <hr>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, vitae, distinctio, possimus repudiandae cupiditate ipsum excepturi dicta neque eaque voluptates tempora veniam esse earum sapiente optio deleniti consequuntur eos voluptatem.</p>

                            <%= form_tag(contact_mailer_path, role: "form") do %>
                                <div class="row">
                                    <div class="form-group col-lg-4">
                                        <%= label_tag(:name, "Name") %>
                                        <%= text_field_tag :name,'', class: "form-control" %>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <%= label_tag(:email, "Email") %>
                                        <%= email_field :email ,'', class: "form-control" %>
                                    </div>
                                    <div class="form-group col-lg-4">
                                        <%= label_tag(:phone_number, "Phone Number") %>
                                        <%= telephone_field :phone_number,'',class: "form-control" %>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="form-group col-lg-12">
                                        <%= label_tag(:content) %>
                                        <%= text_area_tag :content,'', class: "form-control" %>
                                    </div>
                                    <div class="form-group col-lg-12">
                                        <%= submit_tag "Submit", class: "btn btn-default" %>
                                    </div>
                                </div>
                            <% end %>
                </div>
            </div>
        </div>

    </div> 
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

app/views/pages/index.html.erb
<%= provide(:title, "Kohl Kohlbrenner - Portfolio") %>

<!-- use "theme-invert" class on bright backgrounds, also try "text-shadows" class -->
<body class="theme-invert">

<nav class="mainmenu">
    <div class="container">
        <div class="dropdown">
            <button type="button" class="navbar-toggle" data-toggle="dropdown"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <!-- <a data-toggle="dropdown" href="#">Dropdown trigger</a> -->
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li><%= link_to "Hello", "#head", class: "active" %></li>
                <li><a href="#about">About me</a></li>
                <li><a href="#themes">Portfolio</a></li>
                <li><a href="#contact">Get in touch</a></li>
            </ul>
        </div>
    </div>
</nav>


<!-- Main (Home) section -->
<section class="section" id="head">
    <div class="container">

        <div class="row">
            <div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center greeting">

                <!-- Site Title, your name, HELLO msg, etc. -->
                <h1 class="title">Kohl</h1>
                <h2 class="subtitle">Kohlbrenner</h2>

                <!-- Short introductory (optional) -->
                <h3 class="tagline">
                    Fancy seeing you here!<br>
                    You're officially awesome. Now head on over and connect with me!
                </h3>

            </div> <!-- /col -->
        </div> <!-- /row -->

    </div>
</section>

<!-- Second (About) section -->
<section class="section" id="about">
    <div class="container">

        <h2 class="text-center title">About me</h2>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-2">
                <h5><strong>About Me<br></strong></h5>
                <p>
                  My name is Kohl and I live in Saint Louis, MO. For the past few months I have been working at an experience design company called Manifest. We're on our way to becoming one of the biggest
                  Drupal shops in the country. Some of our clients include BMW, Allstate, Delta Faucet, CDW, Marriot, JCK, Brand USA, Post, and you can find even more <%= link_to 'here!', "http://www.manifest.com", :target=>"_blank" %>.
                  Before building websites with PHP, I learned how to code in Ruby and Ruby on Rails. I am really interested in tackling iOS and MVC JavaScript frameworks next! When I'm not coding or working,
                  you might find me running in the park, playing guitar, exploring photography, or sharpening my improv skills.
                </p>
            </div>
            <div class="col-sm-4">
                <h5>
                  <strong>
                    Career Goals<br>
                  </strong>
                </h5>
                <p>
                    I want something spectacular, special, that I can call my own, and of which I created from scratch. Food is super important to me. I love to cook... so much that for a long time I thought about going to culinary school. In my wildest dreams, I see myself on the West Coast
                    at the beach, behind the grill of my beach bar, serving up homemade margaritas and fresh tacos filled with the local catch of the day. I'm a simple man with marvelous dreams.
                  </br>
                    But, until that day comes, I want to build some really cool products and experiences for people!!! The startup grind is really appealing to me. The payoff of long nights(and probably weekends, too) is believe it or not really something I'd enjoy.
                    For me, its about creating something from scratch that hopefully millions of people will find valuable. 
                </p>
            </div>
        </div>
    </div>
</section>

<section class="section" id="themes">
    <div class="container">

        <h2 class="text-center title">Portfolio</h2>

        <div class="row">
            <div class="col-md-12">
            <div class="col-sm-4 col-sm-offset-2 ">
                <div class="thumbnail">
                    <%= image_tag('night.jpeg') %>
                    <div class="caption">
                        <h3>#Pinning</h3>
                        <p>My take on Pinterest</p>
                        <p><%= link_to "Go!", "http://damp-bastion-7658.herokuapp.com", class: "btn btn-default", role: "button" %></p>
                    </div>
                </div>
            </div>

            <div class="col-sm-4 ">
                <div class="thumbnail">
                    <%= image_tag('pelican.jpg') %>
                    <div class="caption">
                        <h3>Twitter clone</h3>
                        <p>A clone of Twitter</p>
                        <p><%= link_to "Go!", "http://twitter-fun.herokuapp.com", class: "btn btn-default", role: "button" %></p>
                    </div>
                </div>
            </div>
            </div>
            <div class="col-md-12">
            <div class="col-sm-4 col-sm-offset-2 ">
                <div class="thumbnail">
                    <%= image_tag('desktop.jpeg') %>
                    <div class="caption">
                        <h3>Daft Magazine</h3>
                        <p>HFC Tech Academy project. Satirical news site. Seeded using Faker.</p>
                        <p><%= link_to "Go!", "http://daftmagazine.herokuapp.com", class: "btn btn-default", role: "button" %></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4 ">
                <div class="thumbnail">
                    <%= image_tag('busy.jpg') %>
                    <div class="caption">
                        <h3>HFC Social Site</h3>
                        <p>Social Networking site for HFC Tech Academy Alumni</p>
                        <p><%= link_to "Go!", "http://lit-forest-6326.herokuapp.com", class: "btn btn-default", role: "button" %></p>
                    </div>
                </div>
            </div>
            </div>
            <div class="col-md-12">
            <div class="col-sm-4 col-sm-offset-2 ">
                <div class="thumbnail">
                    <%= image_tag('coffee.jpeg') %>
                    <div class="caption">
                        <h3>Recipe Site</h3>
                        <p>For personal use. Implemented various backend capabilities to increase learning.</p>
                        <p><a href="http://floating-gorge-1093.herokuapp.com" class="btn btn-default" role="button" >Go!</a></p>

                    </div>
                </div>
            </div>
            <div class="col-sm-4 ">
                <div class="thumbnail">
                    <%= image_tag('clouds.jpeg') %>
                    <div class="caption">
                        <h3>Next Project</h3>
                        <p>Stripe Integration. Coming soon!</p>
                        <p><a href="https://github.com/kohl00/car_mart" class="btn btn-default" role="button">Go!</a></p>
                    </div>
                </div>
            </div>
            </div>

        </div>
        <p class="lead text-center">
            Placeholder images found at <%= link_to "Unsplash", "http://www.unsplash.com" %>
        </p>
    </div>
</section>

<!-- Fourth (Contact) section -->
<section class="section" id="contact">
    <div class="container">

        <h2 class="text-center title">Get in touch</h2>

        <div class="row">
            <div class="col-sm-8 col-sm-offset-2 text-center">
                <ul class="list-inline">
                  <!--<ul class="list-inline list-social"> -->
                    <li>
                      <a href="https://twitter.com/k_kohlbrenner" class="btn btn-link"><i class="fa fa-twitter"></i>Twitter </a>
                    </li>
                    <li>
                      <a href="https://github.com/kohl00" class="btn btn-link"><%= icon('github', 'Github') %> </a>
                    </li>
                    <li>
                      <a href="https://www.linkedin.com/pub/kohl-kohlbrenner/74/123/298" class="btn btn-link"><i class="fa fa-linkedin"></i>LinkedIn </a>
                    </li>
                    <li>
                      <a href="https://medium.com/@kohlkohlbrenner" class="btn btn-link"><%= icon('medium', 'Medium') %> </a>
                    </li>

              </ul>
            </div>
            <div class=" col-sm-12 col-md-6 col-md-offset-3 contact_form">
                <%= form_tag(contact_mailer_path, remote: true, role: "form", id: "contact_form") do %>
                    <div class="row">
                        <div class="form-group col-md-4 col-md-offset-2 col-lg-4">
                            <%= text_field_tag :name,'', placeholder: "Name", class: "form-control" %>
                        </div>
                        <div class="form-group col-lg-4">
                            <%= email_field :email ,'', placeholder: "Email", class: "form-control" %>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group col-lg-12">
                            <%= text_area_tag :content,"Dance like nobody's watching.",class: "form-control" %>
                        </div>
                        <div class="form-group col-lg-12">
                            <%= button_tag "No turning back!", class: "btn btn-default", data: { disable_with: "<i class='fa fa-spinner'></i>" } %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>